function [ Vx, Vy ] = im2mesh_interp(fun, c_grid, f_grid, interp_type)

          Vr = reshape(fun,[size(c_grid(:,1:size(c_grid(:,1)))),2]);  
 switch(interp_type)
     case 'linear'
          Vx = interp2(c_grid(:,1:size(c_grid(:,1))),...
              c_grid(:,1+size(c_grid(:,1)):end),Vr(:,:,1),f_grid(:,1:size(f_grid(:,1))),...
              f_grid(:,1+size(f_grid(:,1)):end),'linear');
          Vy = interp2(c_grid(:,1:size(c_grid(:,1))),...
              c_grid(:,1+size(c_grid(:,1)):end),Vr(:,:,2),f_grid(:,1:size(f_grid(:,1))),...
              f_grid(:,1+size(f_grid(:,1)):end),'linear');

     case 'spline'      
          Vx = interp2(c_grid(:,1:size(c_grid(:,1))),...
              c_grid(:,1+size(c_grid(:,1)):end),Vr(:,:,1),f_grid(:,1:size(f_grid(:,1)))...
              ,f_grid(:,1+size(f_grid(:,1)):end),'spline');
          Vy = interp2(c_grid(:,1:size(c_grid(:,1))),...
              c_grid(:,1+size(c_grid(:,1)):end),Vr(:,:,2),f_grid(:,1:size(f_grid(:,1))),...
              f_grid(:,1+size(f_grid(:,1)):end),'spline');
 end